name: Execução Diário do Robô

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
      - name: clonar repositório
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Commit do relatorio
        run: |
          git add dados/relatorio.csv
          git commit -m "Atualização diária" || echo "Nada para commitar"
          git push
      
